[2024-04-07T03:40:48.281+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_etl.ingest.individual_ingest_movies_rating.download_files_movies_rating manual__2024-04-07T02:56:27.161905+00:00 [queued]>
[2024-04-07T03:40:48.288+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_etl.ingest.individual_ingest_movies_rating.download_files_movies_rating manual__2024-04-07T02:56:27.161905+00:00 [queued]>
[2024-04-07T03:40:48.288+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-07T03:40:48.294+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): ingest.individual_ingest_movies_rating.download_files_movies_rating> on 2024-04-07 02:56:27.161905+00:00
[2024-04-07T03:40:48.298+0000] {standard_task_runner.py:60} INFO - Started process 843 to run task
[2024-04-07T03:40:48.300+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'batch_etl', 'ingest.individual_ingest_movies_rating.download_files_movies_rating', 'manual__2024-04-07T02:56:27.161905+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/batch_etl_dag.py', '--cfg-path', '/tmp/tmpucztyvva']
[2024-04-07T03:40:48.302+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask ingest.individual_ingest_movies_rating.download_files_movies_rating
[2024-04-07T03:40:48.331+0000] {task_command.py:423} INFO - Running <TaskInstance: batch_etl.ingest.individual_ingest_movies_rating.download_files_movies_rating manual__2024-04-07T02:56:27.161905+00:00 [running]> on host befaceac7652
[2024-04-07T03:40:48.394+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_etl' AIRFLOW_CTX_TASK_ID='ingest.individual_ingest_movies_rating.download_files_movies_rating' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T02:56:27.161905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T02:56:27.161905+00:00'
[2024-04-07T03:40:48.397+0000] {logging_mixin.py:188} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2024-04-07T03:40:48.399+0000] {logging_mixin.py:188} INFO - Dataset URL: https://www.kaggle.com/datasets/asaniczka/tmdb-movies-dataset-2023-930k-movies
[2024-04-07T03:41:17.344+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/helpers/ingest.py", line 16, in download_from_kaggle
    api.dataset_download_files(dataset, path = dirpath, unzip = True, quiet = True) # download dataset into DATAPATH
  File "/home/airflow/.local/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 1463, in dataset_download_files
    self.download_file(response, outfile, quiet, not force)
  File "/home/airflow/.local/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 1926, in download_file
    os.utime(outfile,
FileNotFoundError: [Errno 2] No such file or directory
[2024-04-07T03:41:17.405+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=batch_etl, task_id=ingest.individual_ingest_movies_rating.download_files_movies_rating, execution_date=20240407T025627, start_date=20240407T034048, end_date=20240407T034117
[2024-04-07T03:41:17.423+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 62 for task ingest.individual_ingest_movies_rating.download_files_movies_rating ([Errno 2] No such file or directory; 843)
[2024-04-07T03:41:17.467+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-07T03:41:17.516+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
