[2024-04-07T03:32:07.512+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_etl.ingest.individual_ingest_movies_rating manual__2024-04-07T02:56:27.161905+00:00 [queued]>
[2024-04-07T03:32:07.517+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_etl.ingest.individual_ingest_movies_rating manual__2024-04-07T02:56:27.161905+00:00 [queued]>
[2024-04-07T03:32:07.517+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-07T03:32:07.526+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): ingest.individual_ingest_movies_rating> on 2024-04-07 02:56:27.161905+00:00
[2024-04-07T03:32:07.538+0000] {standard_task_runner.py:60} INFO - Started process 582 to run task
[2024-04-07T03:32:07.542+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'batch_etl', 'ingest.individual_ingest_movies_rating', 'manual__2024-04-07T02:56:27.161905+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/batch_etl_dag.py', '--cfg-path', '/tmp/tmp2y6j8lzc']
[2024-04-07T03:32:07.546+0000] {standard_task_runner.py:88} INFO - Job 54: Subtask ingest.individual_ingest_movies_rating
[2024-04-07T03:32:07.578+0000] {task_command.py:423} INFO - Running <TaskInstance: batch_etl.ingest.individual_ingest_movies_rating manual__2024-04-07T02:56:27.161905+00:00 [running]> on host befaceac7652
[2024-04-07T03:32:07.652+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_etl' AIRFLOW_CTX_TASK_ID='ingest.individual_ingest_movies_rating' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T02:56:27.161905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T02:56:27.161905+00:00'
[2024-04-07T03:32:07.663+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/batch_etl_dag.py", line 57, in ingest
    return download >> [upload,load]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 157, in set_downstream
    operator.set_downstream(task_or_task_list, edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(_PythonDecoratedOperator): download_files_movies_rating>, <Task(PythonOperator): uploadingmovies_rating>, <Task(PythonOperator): loadingmovies_rating>]
[2024-04-07T03:32:07.667+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=batch_etl, task_id=ingest.individual_ingest_movies_rating, execution_date=20240407T025627, start_date=20240407T033207, end_date=20240407T033207
[2024-04-07T03:32:07.694+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 54 for task ingest.individual_ingest_movies_rating (Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(_PythonDecoratedOperator): download_files_movies_rating>, <Task(PythonOperator): uploadingmovies_rating>, <Task(PythonOperator): loadingmovies_rating>]; 582)
[2024-04-07T03:32:07.719+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-07T03:32:07.744+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
