[2024-04-07T04:40:14.314+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T04:40:12.501629+00:00 [queued]>
[2024-04-07T04:40:14.318+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T04:40:12.501629+00:00 [queued]>
[2024-04-07T04:40:14.319+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-07T04:40:14.325+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): set_up_datawarehouse> on 2024-04-07 04:40:12.501629+00:00
[2024-04-07T04:40:14.328+0000] {standard_task_runner.py:60} INFO - Started process 3878 to run task
[2024-04-07T04:40:14.330+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'setup', 'set_up_datawarehouse', 'manual__2024-04-07T04:40:12.501629+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpph45ntwc']
[2024-04-07T04:40:14.333+0000] {standard_task_runner.py:88} INFO - Job 199: Subtask set_up_datawarehouse
[2024-04-07T04:40:14.359+0000] {task_command.py:423} INFO - Running <TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T04:40:12.501629+00:00 [running]> on host befaceac7652
[2024-04-07T04:40:14.399+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='setup' AIRFLOW_CTX_TASK_ID='set_up_datawarehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T04:40:12.501629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T04:40:12.501629+00:00'
[2024-04-07T04:40:14.453+0000] {warehouse.py:54} ERROR - Database already exists!!
[2024-04-07T04:40:14.454+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'dashboard'}
[2024-04-07T04:40:14.532+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:40:14.532+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'dashboard'}
[2024-04-07T04:40:14.726+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:40:14.726+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'dashboard'}
[2024-04-07T04:40:14.751+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:40:14.778+0000] {warehouse.py:54} ERROR - Database already exists!!
[2024-04-07T04:40:14.779+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'machinelearning'}
[2024-04-07T04:40:14.817+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:40:14.818+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'machinelearning'}
[2024-04-07T04:40:14.858+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:40:14.859+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'machinelearning'}
[2024-04-07T04:40:14.885+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:40:14.910+0000] {warehouse.py:54} ERROR - Database already exists!!
[2024-04-07T04:40:14.911+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'datawarehouse'}
[2024-04-07T04:40:14.955+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:40:14.956+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'datawarehouse'}
[2024-04-07T04:40:14.990+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:40:14.990+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'datawarehouse'}
[2024-04-07T04:40:15.014+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:40:15.015+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-07T04:40:15.021+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=setup, task_id=set_up_datawarehouse, execution_date=20240407T044012, start_date=20240407T044014, end_date=20240407T044015
[2024-04-07T04:40:15.055+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-07T04:40:15.071+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
