[2024-04-07T04:50:52.999+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T04:50:51.051745+00:00 [queued]>
[2024-04-07T04:50:53.003+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T04:50:51.051745+00:00 [queued]>
[2024-04-07T04:50:53.003+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-07T04:50:53.009+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): set_up_datawarehouse> on 2024-04-07 04:50:51.051745+00:00
[2024-04-07T04:50:53.012+0000] {standard_task_runner.py:60} INFO - Started process 5157 to run task
[2024-04-07T04:50:53.014+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'setup', 'set_up_datawarehouse', 'manual__2024-04-07T04:50:51.051745+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpzrrkppf1']
[2024-04-07T04:50:53.016+0000] {standard_task_runner.py:88} INFO - Job 262: Subtask set_up_datawarehouse
[2024-04-07T04:50:53.038+0000] {task_command.py:423} INFO - Running <TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T04:50:51.051745+00:00 [running]> on host befaceac7652
[2024-04-07T04:50:53.072+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='setup' AIRFLOW_CTX_TASK_ID='set_up_datawarehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T04:50:51.051745+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T04:50:51.051745+00:00'
[2024-04-07T04:50:53.129+0000] {warehouse.py:54} ERROR - Database already exists!!
[2024-04-07T04:50:53.130+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'dashboard', 'allow_local_infile': True}
[2024-04-07T04:50:53.185+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:50:53.185+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'dashboard', 'allow_local_infile': True}
[2024-04-07T04:50:53.219+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:50:53.219+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'dashboard', 'allow_local_infile': True}
[2024-04-07T04:50:53.243+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:50:53.271+0000] {warehouse.py:54} ERROR - Database already exists!!
[2024-04-07T04:50:53.272+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'machinelearning', 'allow_local_infile': True}
[2024-04-07T04:50:53.309+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:50:53.309+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'machinelearning', 'allow_local_infile': True}
[2024-04-07T04:50:53.340+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:50:53.340+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'machinelearning', 'allow_local_infile': True}
[2024-04-07T04:50:53.366+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:50:53.398+0000] {warehouse.py:54} ERROR - Database already exists!!
[2024-04-07T04:50:53.399+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'datawarehouse', 'allow_local_infile': True}
[2024-04-07T04:50:53.447+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:50:53.447+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'datawarehouse', 'allow_local_infile': True}
[2024-04-07T04:50:53.479+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:50:53.480+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'datawarehouse', 'allow_local_infile': True}
[2024-04-07T04:50:53.502+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:50:53.503+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-07T04:50:53.508+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=setup, task_id=set_up_datawarehouse, execution_date=20240407T045051, start_date=20240407T045053, end_date=20240407T045053
[2024-04-07T04:50:53.523+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-07T04:50:53.538+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
