[2024-04-07T04:53:48.053+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T04:53:45.707365+00:00 [queued]>
[2024-04-07T04:53:48.057+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T04:53:45.707365+00:00 [queued]>
[2024-04-07T04:53:48.058+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-07T04:53:48.063+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): set_up_datawarehouse> on 2024-04-07 04:53:45.707365+00:00
[2024-04-07T04:53:48.068+0000] {standard_task_runner.py:60} INFO - Started process 5590 to run task
[2024-04-07T04:53:48.070+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'setup', 'set_up_datawarehouse', 'manual__2024-04-07T04:53:45.707365+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpd9yj0pt6']
[2024-04-07T04:53:48.071+0000] {standard_task_runner.py:88} INFO - Job 287: Subtask set_up_datawarehouse
[2024-04-07T04:53:48.095+0000] {task_command.py:423} INFO - Running <TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T04:53:45.707365+00:00 [running]> on host befaceac7652
[2024-04-07T04:53:48.134+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='setup' AIRFLOW_CTX_TASK_ID='set_up_datawarehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T04:53:45.707365+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T04:53:45.707365+00:00'
[2024-04-07T04:53:48.194+0000] {warehouse.py:54} ERROR - Database already exists!!
[2024-04-07T04:53:48.195+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'dashboard', 'allow_local_infile': True}
[2024-04-07T04:53:48.251+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:53:48.251+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'dashboard', 'allow_local_infile': True}
[2024-04-07T04:53:48.311+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:53:48.313+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'dashboard', 'allow_local_infile': True}
[2024-04-07T04:53:48.348+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:53:48.373+0000] {warehouse.py:54} ERROR - Database already exists!!
[2024-04-07T04:53:48.374+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'machinelearning', 'allow_local_infile': True}
[2024-04-07T04:53:48.406+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:53:48.407+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'machinelearning', 'allow_local_infile': True}
[2024-04-07T04:53:48.442+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:53:48.443+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'machinelearning', 'allow_local_infile': True}
[2024-04-07T04:53:48.468+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:53:48.495+0000] {warehouse.py:54} ERROR - Database already exists!!
[2024-04-07T04:53:48.496+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'datawarehouse', 'allow_local_infile': True}
[2024-04-07T04:53:48.612+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:53:48.613+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'datawarehouse', 'allow_local_infile': True}
[2024-04-07T04:53:48.654+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:53:48.655+0000] {warehouse.py:75} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***', 'database': 'datawarehouse', 'allow_local_infile': True}
[2024-04-07T04:53:48.681+0000] {warehouse.py:95} INFO - SUCCESSFULLY EXECUTED QUERIES
[2024-04-07T04:53:48.682+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-07T04:53:48.688+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=setup, task_id=set_up_datawarehouse, execution_date=20240407T045345, start_date=20240407T045348, end_date=20240407T045348
[2024-04-07T04:53:48.701+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-07T04:53:48.717+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
