[2024-04-07T04:00:23.471+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T03:54:58.082620+00:00 [queued]>
[2024-04-07T04:00:23.476+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T03:54:58.082620+00:00 [queued]>
[2024-04-07T04:00:23.476+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 5
[2024-04-07T04:00:23.483+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): set_up_datawarehouse> on 2024-04-07 03:54:58.082620+00:00
[2024-04-07T04:00:23.486+0000] {standard_task_runner.py:60} INFO - Started process 1351 to run task
[2024-04-07T04:00:23.487+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'setup', 'set_up_datawarehouse', 'manual__2024-04-07T03:54:58.082620+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpj3v5gyhx']
[2024-04-07T04:00:23.489+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask set_up_datawarehouse
[2024-04-07T04:00:23.511+0000] {task_command.py:423} INFO - Running <TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T03:54:58.082620+00:00 [running]> on host befaceac7652
[2024-04-07T04:00:23.544+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='setup' AIRFLOW_CTX_TASK_ID='set_up_datawarehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T03:54:58.082620+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T03:54:58.082620+00:00'
[2024-04-07T04:00:23.594+0000] {warehouse.py:38} ERROR - Database already exists!!
[2024-04-07T04:00:23.595+0000] {warehouse.py:59} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***'}
[2024-04-07T04:00:23.631+0000] {warehouse.py:76} ERROR - 1046 (3D000): No database selected
[2024-04-07T04:00:23.631+0000] {warehouse.py:59} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***'}
[2024-04-07T04:00:23.664+0000] {warehouse.py:76} ERROR - 1046 (3D000): No database selected
[2024-04-07T04:00:23.696+0000] {warehouse.py:38} ERROR - Database already exists!!
[2024-04-07T04:00:23.697+0000] {warehouse.py:59} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***'}
[2024-04-07T04:00:23.732+0000] {warehouse.py:76} ERROR - 1046 (3D000): No database selected
[2024-04-07T04:00:23.732+0000] {warehouse.py:59} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***'}
[2024-04-07T04:00:23.765+0000] {warehouse.py:76} ERROR - 1046 (3D000): No database selected
[2024-04-07T04:00:23.798+0000] {warehouse.py:38} ERROR - Database already exists!!
[2024-04-07T04:00:23.799+0000] {warehouse.py:59} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***'}
[2024-04-07T04:00:23.833+0000] {warehouse.py:76} ERROR - 1046 (3D000): No database selected
[2024-04-07T04:00:23.834+0000] {warehouse.py:59} INFO - {'host': 'host.docker.internal', 'user': 'root', 'password': '***'}
[2024-04-07T04:00:23.865+0000] {warehouse.py:76} ERROR - 1046 (3D000): No database selected
[2024-04-07T04:00:23.865+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-07T04:00:23.870+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=setup, task_id=set_up_datawarehouse, execution_date=20240407T035458, start_date=20240407T040023, end_date=20240407T040023
[2024-04-07T04:00:23.913+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-07T04:00:23.926+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
