[2024-04-07T03:58:12.896+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T03:54:58.082620+00:00 [queued]>
[2024-04-07T03:58:12.900+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T03:54:58.082620+00:00 [queued]>
[2024-04-07T03:58:12.901+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-04-07T03:58:12.907+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): set_up_datawarehouse> on 2024-04-07 03:54:58.082620+00:00
[2024-04-07T03:58:12.910+0000] {standard_task_runner.py:60} INFO - Started process 1300 to run task
[2024-04-07T03:58:12.912+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'setup', 'set_up_datawarehouse', 'manual__2024-04-07T03:54:58.082620+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmphw2mc8q1']
[2024-04-07T03:58:12.914+0000] {standard_task_runner.py:88} INFO - Job 87: Subtask set_up_datawarehouse
[2024-04-07T03:58:12.936+0000] {task_command.py:423} INFO - Running <TaskInstance: setup.set_up_datawarehouse manual__2024-04-07T03:54:58.082620+00:00 [running]> on host befaceac7652
[2024-04-07T03:58:12.973+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='setup' AIRFLOW_CTX_TASK_ID='set_up_datawarehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T03:54:58.082620+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T03:54:58.082620+00:00'
[2024-04-07T03:58:13.027+0000] {warehouse.py:38} ERROR - Database already exists!!
[2024-04-07T03:58:13.061+0000] {warehouse.py:75} ERROR - 1046 (3D000): No database selected
[2024-04-07T03:58:13.095+0000] {warehouse.py:75} ERROR - 1046 (3D000): No database selected
[2024-04-07T03:58:13.136+0000] {warehouse.py:38} ERROR - Database already exists!!
[2024-04-07T03:58:13.175+0000] {warehouse.py:75} ERROR - 1046 (3D000): No database selected
[2024-04-07T03:58:13.217+0000] {warehouse.py:75} ERROR - 1046 (3D000): No database selected
[2024-04-07T03:58:13.258+0000] {warehouse.py:38} ERROR - Database already exists!!
[2024-04-07T03:58:13.295+0000] {warehouse.py:75} ERROR - 1046 (3D000): No database selected
[2024-04-07T03:58:13.336+0000] {warehouse.py:75} ERROR - 1046 (3D000): No database selected
[2024-04-07T03:58:13.337+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-07T03:58:13.344+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=setup, task_id=set_up_datawarehouse, execution_date=20240407T035458, start_date=20240407T035812, end_date=20240407T035813
[2024-04-07T03:58:13.381+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-07T03:58:13.399+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
