[2024-04-07T03:21:35.897+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_etl.loadingmovies_casts manual__2024-04-07T02:56:27.161905+00:00 [queued]>
[2024-04-07T03:21:35.913+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_etl.loadingmovies_casts manual__2024-04-07T02:56:27.161905+00:00 [queued]>
[2024-04-07T03:21:35.914+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-07T03:21:35.937+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): loadingmovies_casts> on 2024-04-07 02:56:27.161905+00:00
[2024-04-07T03:21:35.942+0000] {standard_task_runner.py:60} INFO - Started process 259 to run task
[2024-04-07T03:21:35.965+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'batch_etl', 'loadingmovies_casts', 'manual__2024-04-07T02:56:27.161905+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/batch_etl_dag.py', '--cfg-path', '/tmp/tmpwom37db1']
[2024-04-07T03:21:35.974+0000] {standard_task_runner.py:88} INFO - Job 47: Subtask loadingmovies_casts
[2024-04-07T03:21:36.076+0000] {task_command.py:423} INFO - Running <TaskInstance: batch_etl.loadingmovies_casts manual__2024-04-07T02:56:27.161905+00:00 [running]> on host befaceac7652
[2024-04-07T03:21:36.215+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_etl' AIRFLOW_CTX_TASK_ID='loadingmovies_casts' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T02:56:27.161905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T02:56:27.161905+00:00'
[2024-04-07T03:21:36.217+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/database/warehouse.py", line 117, in load_from_csv_batch_sql
    set_part = ', '.join([f'{column_mapping[column]}=@{column}' for column in columns])
  File "/opt/airflow/dags/database/warehouse.py", line 117, in <listcomp>
    set_part = ', '.join([f'{column_mapping[column]}=@{column}' for column in columns])
KeyError: 'id'
[2024-04-07T03:21:36.226+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=batch_etl, task_id=loadingmovies_casts, execution_date=20240407T025627, start_date=20240407T032135, end_date=20240407T032136
[2024-04-07T03:21:36.235+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 47 for task loadingmovies_casts ('id'; 259)
[2024-04-07T03:21:36.274+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-07T03:21:36.293+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
